<a href="https://colab.research.google.com/github/SigmaRajput/ML_classes_2022/blob/master/16th_aug_lec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Raggged tensor
# matrix having irregular number of columns for each row
# eg: 0 1 3 4
#     3 4
#     1 4 3
#     4

In [1]:
import tensorflow as tf

In [3]:
ragged_list =[
    [0,1,2,3],
    [4,5],
    [6,7,8],
    [9]
]
print(ragged_list)

try:
  ragged_tensor = tf.ragged.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")
print(ragged_tensor)

[[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]
<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [4]:
scalar_string_tensor = tf.constant("Gray wolf")
# rank 0
print(scalar_string_tensor)

tensor_of_string = tf.constant(["Gray wolf", "Quick brown fox", "Lazy dog"])
# rank 1
print(tensor_of_string)


tf.Tensor(b'Gray wolf', shape=(), dtype=string)
tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


In [9]:
print(tf.strings.split(scalar_string_tensor, sep =" "))
# seperated on the basis of seperator passed
print(tf.strings.split(tensor_of_string))
# it will convert to a list of list

tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)
<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>


In [10]:
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
# Split byte by byte for a given string
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)
# respective byte string value(ASCII) conversion
print("Byte strings:", byte_strings)
print("Bytes:", byte_ints)

Byte strings: tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)
Bytes: tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)


In [13]:
sparse_tensor = tf.sparse.SparseTensor(indices = [[0,0], [1,2]],
                                      values = [1,2],
                                      dense_shape = [3,4])
print(sparse_tensor,"\n")
print(tf.sparse.to_dense(sparse_tensor))


SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [11]:
rank_4_tensor=tf.zeros([3,2,4,5])
# rank 4 :[ Batch, width, Height,Features]
print("Type of every element:",rank_4_tensor.dtype)
print("number of Dimentions:",rank_4_tensor.ndim)
print("shape of tensor:",rank_4_tensor.shape)
print("Element along axis 0 of tensor:",rank_4_tensor.shape[0])
print("Element along last axis of tensor:",rank_4_tensor.shape[1])
print("Total number of elements(3*2*4*5):",tf.size(rank_4_tensor).numpy)

Type of every element: <dtype: 'float32'>
number of Dimentions: 4
shape of tensor: (3, 2, 4, 5)
Element along axis 0 of tensor: 3
Element along last axis of tensor: 2
Total number of elements(3*2*4*5): <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=120>>
